### ISSUE TITLE
Chocolatey install build

### ISSUE THREAD

**Issue by abbottdev** [JakeGinnivan/GitReleaseNotes#65]
Hi,

Latest version on chocolatey is v.0.5.0 - Is chocolatey included as a target in your package target, or is there just a delay?

https://chocolatey.org/packages?q=gitreleasenotes&prerelease=true&sortOrder=relevance

Thanks

**Comment by JakeGinnivan** [comment]
It's submitted waiting to be approved

Sent from my Windows Phone
________________________________

**Comment by abbottdev** [comment]
Thanks
