### ISSUE TITLE
Add /AllLabels argument to allow all label to be a category

### ISSUE THREAD

**Issue by laedit** [JakeGinnivan/GitReleaseNotes#69]
Right now I have to define the categories I want that GitReleaseNotes use with the /Categories but in the case that I want all labels to be used as categories I think it'll be easier to juste use a /AllLabels (or /AllCategories or /AllLabelsAsCategories, I'm not good with names).

If you are ok with the idea I'd be happy to propose a PR :smiley:

**Comment by JakeGinnivan** [comment]
Sure, I am happy to add you as a contributor to this project too. I am short on time and if you are finding this useful happy for you to help out :) I can review/merge your stuff still

**Comment by laedit** [comment]
Thanks, I'll propose a PR in about a week I think.

**Comment by JakeGinnivan** [comment]
Do you think this should be the default?

**Comment by laedit** [comment]
Well even if that'll make easier my use of GitReleaseNotes I don't think it should be the default:
 - it'll be a breaking change
 - most of the projects on GitHub use a lot of labels to indicate the priority, the state or other things about an issue and I don't think it's the kind of things people want to have in a release notes

I can be wrong, it depends on how people manage their labels but I think that to have the option is sufficient.

**Comment by JakeGinnivan** [comment]
Thats fine, happy leaving it. Just thought id ask.

**Comment by laedit** [comment]
Thanks for the thought :smiley:
